### ISSUE TITLE
Missing tag for 0.3.0

### ISSUE THREAD

**Issue by alyssais** [DuckerMan/magnum-opus#2]

**Comment by TheRadioGuy** [comment]
Thank you, I fixed it :)

**Comment by alyssais** [comment]
It doesn’t look like you did, I’m afraid. I still don’t see any version later than 0.2.0: https://github.com/DuckerMan/magnum-opus/releases

**Comment by TheRadioGuy** [comment]
Uh, sorry. I thought you meant releases on crates.io. Fixed

**Comment by alyssais** [comment]
> Uh, sorry. I thought you meant releases on crates.io. Fixed

Sweet, thank you!
